name: Run Tests
on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies (including dev)
        run: |
          uv pip install -e .[dev] --system

      - name: Run tests with coverage
        run: |
          pytest --cov=src/crowdcent_challenge --cov-report=xml --cov-fail-under=70

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        env:
           CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: ./coverage.xml